version: "2"

services:
    php:
        build:
            dockerfile: Dockerfile
            context: ./php
        links:
            - mariadb
            - redis
        volumes:
            - "../..:/code:rw"
            - "./php/local.xml:/code/http/app/etc/local.xml"
            - "./php/n98-magerun.phar:/code/n98-magerun.phar"
        networks:
            - web
        #command: mount -t overlay -o lowerdir=/code-src,upperdir=/var/local-code,workdir=/var/workdir none /code
        #mount -t aufs -o br=/var/local-code:/code-src none /code/
    mariadb:
        build:
            dockerfile: Dockerfile
            context: ./db
        environment:
            - "MYSQL_ROOT_PASSWORD=rootpassword"
            - "MYSQL_DATABASE=magentodb"
            - "MYSQL_USER=magento"
            - "MYSQL_PASSWORD=magento"
        volumes:
            - "./db/mariadb:/var/lib/mysql:rw"
            - "./db/conf.d:/etc/mysql/conf.d"
        #command: mysql -u magento -pmagento magentodb < /tmp/update.sql
        networks:
            - web
        expose:
            - "3306"
    redis:
        image: redis:latest
        networks:
            - web
    web:
        image: nginx:latest
        expose:
            - "80"
        links:
            - php
        volumes:
            - "../..:/code:rw"
            - "./web/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./web/nginx/fastcgi_params:/etc/nginx/fastcgi_params"
            - "./web/nginx/conf_m1/:/etc/nginx/conf_m1/"
            - "./web/nginx/sites-available/:/etc/nginx/sites-available/"
            - "./web/nginx/sites-enabled/:/etc/nginx/sites-enabled/"
        depends_on:
            - php
        labels:
            - "traefik.backend=${COMPOSE_PROJECT_NAME}_web_1"
            - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.webpipeline.co.uk"
        networks:
            - web
networks:
    web:
        external:
            name: traefik_webgateway
